### ISSUE TITLE
browser page zoom doesn't work

### ISSUE THREAD

**Issue by mark-hahn** [BillyBlaze/OctoPrint-FullScreen#23]
When I zoom the page the video stays the same size while everything else scales.  I frequently zoom into video in apps and it would be particularly useful for looking closer at prints.

I assume this is just a matter of some CSS.

**Comment by BillyBlaze** [comment]
Thanks for reporting. I have looked into it and this is sadly not simple, it was just CSS I would consider this request. In a nutshell: in order to zoom on images you need to set width and height on the image. So that means we have to calculate that width in JS, however when zooming the page reports the width of the zoomed page not the real page width. That is just one of the problems.

I would suggest to right click on the image and open it in a new tab where you can freely zoom.
